### ISSUE TITLE
Error on Dependency Injection

### ISSUE THREAD

**Issue by gurgenhakobyan** [harentius/facebook-bundle#1]
Hi. I'm getting this error PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/dev/vendor/harentius/facebook-bundle/src/DependencyInjection/HarentiusFacebookExtension.php on line 20

I guess it's from php version, we have 5.4.45. Is it possible to fix this that version?

Thanks.

**Comment by harentius** [comment]
Thanks for reporting!
Just fixed in version v1.0.4

**Comment by gurgenhakobyan** [comment]
Thanks a lot :+1:

**Comment by harentius** [comment]
You're welcome!
